requires 'Mojolicious';
requires 'Mojo::DOM';
requires 'Mojo::JSON';
requires 'Mojo::URL';
requires 'Mojo::UserAgent';
requires 'Try::Tiny';
requires 'Lingua::EN::Opinion';
requires 'WordNet::QueryData';
requires 'WordNet::Similarity';
